# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PotentialMusicStartUpApplication' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PotentialMusicStartUpApplication

	pod ‘Alamofire’
	pod ‘RxSwift’
	pod ‘RxCocoa’
	pod ’SnapKit’
	pod ‘RxDataSources’
	pod ‘RxAlamofire’

  target 'PotentialMusicStartUpApplicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
